### ISSUE TITLE
npm  run ask error

### ISSUE THREAD

**Issue by wangxin1999** [wuomzfx/pdfGPT#2]
/usr/local/bin/npm run ask

> pdf-gpt@1.0.0 ask
> node ./scripts/ask

AI 正在努力回答您的问题『语言能力完全丧失或严重咀嚼吞咽功能障碍:』，请稍作等待...

./pdfGPT-main/utils/ask.js:13
  const kList = knowledgeEmbeddings.map((knowledge, index) => {
                                    ^

TypeError: knowledgeEmbeddings.map is not a function
    at getKnowledge (./pdfGPT-main/utils/ask.js:13:37)
    at ask (./pdfGPT-main/utils/ask.js:39:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async askQuestion (./pdfGPT-main/index.js:21:18)
    at async ./pdfGPT-main/scripts/ask.js:9:5

Node.js v18.15.0

Process finished with exit code 1

**Comment by wangxin1999** [comment]
const fs = require('fs');
const path = require('path');
const { encode } = require('gpt-3-encoder');
const ddot = require('@stdlib/blas/base/ddot');

const { buildQuestionEmbedding } = require('./embedding');
const { writeAnswer } = require('./fs');
const { askInsQuestion } = require('./ai');

async function ask(question, pdfName) {
  const questionEmbedding = await buildQuestionEmbedding(question, pdfName);

  const knowledgeDir = path.join(__dirname, '..', 'knowledgeFiles', pdfName);
  const knowledgeEmbeddings = fs
    .readdirSync(knowledgeDir)
    .filter(filename => path.extname(filename) === '.json')
    .map(filename => require(path.join(knowledgeDir, filename)));

  const knowledgeList = knowledgeEmbeddings.map(k => k.text);

  const kList = knowledgeEmbeddings
    .map((knowledge, index) => {
      const x = new Float64Array(questionEmbedding);
      const y = new Float64Array(knowledge.embedding);
      return {
        index,
        ddot: ddot(x.length, x, 1, y, 1),
        knowledge: knowledgeList[index],
      };
    })
    .sort((a, b) => b.ddot - a.ddot)
    .filter(k => k.ddot > 0.8);

  let tokens = 0;
  const enoughTokenList = kList.filter(k => {
    tokens += encode(k.knowledge).length;
    return tokens < 3000;
  });

  const knowledge = enoughTokenList.map(({ knowledge }) => knowledge).join('\n');
  const answer = await askInsQuestion({ question, knowledge });
  writeAnswer(pdfName, question, answer);
  return answer;
}

module.exports = ask;

换成这个work了
