### ISSUE TITLE
执行 npm run load 提示以下错误

### ISSUE THREAD

**Issue by yenava** [wuomzfx/pdfGPT#4]
ReferenceError: structuredClone is not defined
    at LoopbackPort.postMessage (/Users/yanhui/code/pdfGPT-main/node_modules/pdfjs-dist/build/pdf.js:1709:13)
    at MessageHandler.sendWithPromise (/Users/yanhui/code/pdfGPT-main/node_modules/pdfjs-dist/build/pdf.js:7779:19)
    at _fetchDocument (/Users/yanhui/code/pdfGPT-main/node_modules/pdfjs-dist/build/pdf.js:1067:48)
    at /Users/yanhui/code/pdfGPT-main/node_modules/pdfjs-dist/build/pdf.js:1026:29

**Comment by wuomzfx** [comment]
https://github.com/mozilla/pdf.js/issues/14729

**Comment by yenava** [comment]
node版本太久，更新node即可

**Comment by yenava** [comment]
run load显示超时，是梯子的问题吗？
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

<ref *1> Error: connect ETIMEDOUT 162.125.2.5:443

**Comment by wuomzfx** [comment]
可以自己裸掉一下试试看，不行的话试试：

export HTTPS_PROXY=http://127.0.0.1:10080 

10080，是我 梯子的端口，你得看看你的

**Comment by yenava** [comment]
改了端口，报403，写了个简单请求试了下key是可以用的
/Users/yanhui/code/pdfGPT-main/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^

Error: Request failed with status code 403
    at createError (/Users/yanhui/code/pdfGPT-main/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/yanhui/code/pdfGPT-main/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/yanhui/code/pdfGPT-main/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by yenava** [comment]
请求提示：The OpenAI API can only be accessed over HTTPS. You should access https://api.openai.com rather than the current URL.',  
但我的current URL为https://api.openai.com/v1/completions

**Comment by wuomzfx** [comment]
自从国内ban了后，我也没怎么调用过了，辛苦先自己研究一下~

**Comment by tanabalu** [comment]
> node版本太久，更新node即可

请问node升级到什么版本解决了这个问题
